### ISSUE TITLE
Create package for this repo

### ISSUE THREAD

**Issue by JanMikes** [dflydev/git-subsplit#34]
Hello there!

I would love to use subsplit in CI (travis cron triggered job), and it would be awesome if it was possible to install subsplit by some package manager (composer, npm etc.).

Were you thinking about that? It is definitely something i could help you with!

Right now we are failing on this: https://travis-ci.org/Symplify/Symplify/jobs/394514575#L702

**Comment by themightychris** [comment]
ohh good idea, I'll volunteer to make a habitat package!

Edit: see #35

**Comment by TomasVotruba** [comment]
In Symplify we resolved by adding own split command on top of this, see https://github.com/Symplify/Symplify/pull/932

## Install

```bash
composer require symplify/monorepo-builder --dev
```


## Use 

It supports paralel run which makes it much faster.

Classic use case for monorepo is to synchronize last tag and the `master` branch to allow testing of `@dev` version.

```yaml
# monorepo-builder.yml
parameters:
    directories_to_repositories:
        packages/BetterPhpDocParser: 'git@github.com:Symplify/BetterPhpDocParser.git'
        packages/PackageBuilder: 'git@github.com:Symplify/PackageBuilder.git'
```

And run by:

```bash
vendor/bin/monorepo-builder package-alias
```
